<a href="https://colab.research.google.com/github/swopnimghimire-123123/data-analysis-visualization/blob/main/05_Group_By_Aggregation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

###**GroupBy**

In [ ]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}

In [ ]:
df = pd.DataFrame(data)

In [ ]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [ ]:
# Group by catagory and calculate the sum of sales
category_sales = df.groupby('Category')['Sales'].sum()
category_sales

Category
A    570
B    930
Name: Sales, dtype: int64

In [ ]:
# Group by store and calculate the sum of sales
store_sales = df.groupby('Store')['Sales'].sum()
store_sales

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [ ]:
# Gropu by multiple columns
# Group by catagory and store
category_store_sales = df.groupby(['Category', 'Store'])['Sales'].sum()
category_store_sales

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [ ]:
# Swapping the values
category_store_sales = df.groupby(['Store', 'Category'])['Sales'].sum()
category_store_sales

Store  Category
S1     A           220
       B           500
S2     A           350
       B           430
Name: Sales, dtype: int64

### **Aggregation**

In [ ]:
df["Sales"].mean()
# mean medina min max count std

np.float64(187.5)

In [ ]:
df["Sales"].agg(["mean", "median", "min", "max", "count", "std"])

mean      187.500000
median    190.000000
min       100.000000
max       300.000000
count       8.000000
std        66.062741
Name: Sales, dtype: float64